server:
  port: ${PORT:8080}
spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
eureka:
  client:
    service-url:
      defaultZone: https://serviceregistry-bugbusters.onrender.com/eureka